export interface Exercise {
  id: string;
  name: string;
  nameUrdu: string;
  nameJapanese: string;
  muscleGroup: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  equipment: string;
  bodyPart: string;
  youtubeId: string;
  thumbnail: string;
  duration: string;
  sets: string;
  reps: string;
  description: string;
  descriptionUrdu: string;
  instructions: string[];
  calories: number;
}

export const exercises: Exercise[] = [
  {
    id: '1',
    name: 'Barbell Bench Press',
    nameUrdu: 'بیریل بنچ پریس',
    nameJapanese: 'バーベルベンチプレス',
    muscleGroup: 'Chest',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    bodyPart: 'Upper Body',
    youtubeId: 'rT7DgCr-3pg',
    thumbnail: 'https://img.youtube.com/vi/rT7DgCr-3pg/maxresdefault.jpg',
    duration: '45 min',
    sets: '4',
    reps: '8-12',
    description: 'The king of chest exercises. Builds massive pecs and upper body strength.',
    descriptionUrdu: 'چھاتی کی ورزشوں کا بادشاہ۔ بڑے پیکس اور اوپری جسم کی طاقت بناتا ہے۔',
    instructions: [
      'Lie flat on bench, grip bar slightly wider than shoulder width',
      'Unrack bar and lower to chest with control',
      'Press explosively back to starting position',
      'Keep core tight and feet planted'
    ],
    calories: 120
  },
  {
    id: '2',
    name: 'Pull-Ups',
    nameUrdu: 'پل اپس',
    nameJapanese: '懸垂',
    muscleGroup: 'Back',
    difficulty: 'Intermediate',
    equipment: 'Pull-up Bar',
    bodyPart: 'Upper Body',
    youtubeId: 'eGo4IYlbE5g',
    thumbnail: 'https://img.youtube.com/vi/eGo4IYlbE5g/maxresdefault.jpg',
    duration: '30 min',
    sets: '4',
    reps: '6-10',
    description: 'Ultimate back width builder. Develops lat muscles and overall back strength.',
    descriptionUrdu: 'پشت کی چوڑائی بنانے کا بہترین طریقہ۔ لیٹ مسلز اور پشت کی طاقت بناتا ہے۔',
    instructions: [
      'Hang from bar with overhand grip, hands shoulder-width apart',
      'Pull body up until chin is above bar',
      'Lower slowly with control',
      'Avoid swinging or kipping'
    ],
    calories: 100
  },
  {
    id: '3',
    name: 'Barbell Squat',
    nameUrdu: 'باربل اسکواٹ',
    nameJapanese: 'バーベルスクワット',
    muscleGroup: 'Legs',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    bodyPart: 'Lower Body',
    youtubeId: 'ultWZbUMPL8',
    thumbnail: 'https://img.youtube.com/vi/ultWZbUMPL8/maxresdefault.jpg',
    duration: '50 min',
    sets: '5',
    reps: '5-8',
    description: 'The ultimate leg builder. Squats develop quads, hamstrings, glutes and core.',
    descriptionUrdu: 'ٹانگوں کا سب سے بہترین ورزش۔ کواڈز، ہیمسٹرنگ، گلوٹس اور کور بناتا ہے۔',
    instructions: [
      'Place bar on upper traps, feet shoulder-width apart',
      'Break at hips and knees simultaneously',
      'Squat until thighs are parallel to floor',
      'Drive through heels to stand'
    ],
    calories: 200
  },
  {
    id: '4',
    name: 'Deadlift',
    nameUrdu: 'ڈیڈلفٹ',
    nameJapanese: 'デッドリフト',
    muscleGroup: 'Back',
    difficulty: 'Advanced',
    equipment: 'Barbell',
    bodyPart: 'Full Body',
    youtubeId: 'op9kVnSso6Q',
    thumbnail: 'https://img.youtube.com/vi/op9kVnSso6Q/maxresdefault.jpg',
    duration: '45 min',
    sets: '4',
    reps: '4-6',
    description: 'The most powerful compound movement. Builds total body strength and muscle mass.',
    descriptionUrdu: 'سب سے طاقتور مرکب حرکت۔ پورے جسم کی طاقت اور پٹھوں کی کثافت بناتا ہے۔',
    instructions: [
      'Stand with feet hip-width apart, bar over mid-foot',
      'Hinge at hips, grip bar just outside legs',
      'Keep spine neutral, chest up',
      'Drive feet into floor and pull bar up along legs'
    ],
    calories: 250
  },
  {
    id: '5',
    name: 'Overhead Press',
    nameUrdu: 'اوور ہیڈ پریس',
    nameJapanese: 'オーバーヘッドプレス',
    muscleGroup: 'Shoulders',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    bodyPart: 'Upper Body',
    youtubeId: '2yjwXTZQDDI',
    thumbnail: 'https://img.youtube.com/vi/2yjwXTZQDDI/maxresdefault.jpg',
    duration: '40 min',
    sets: '4',
    reps: '6-10',
    description: 'Builds boulder shoulders and total upper body pressing strength.',
    descriptionUrdu: 'بڑے کندھے اور اوپری جسم کی پریسنگ طاقت بناتا ہے۔',
    instructions: [
      'Stand with bar at collarbone height',
      'Press bar straight overhead',
      'Lock out elbows at top',
      'Lower bar back to starting position'
    ],
    calories: 130
  },
  {
    id: '6',
    name: 'Dumbbell Curl',
    nameUrdu: 'ڈمبل کرل',
    nameJapanese: 'ダンベルカール',
    muscleGroup: 'Arms',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    bodyPart: 'Upper Body',
    youtubeId: 'ykJmrZ5v0Oo',
    thumbnail: 'https://img.youtube.com/vi/ykJmrZ5v0Oo/maxresdefault.jpg',
    duration: '30 min',
    sets: '3',
    reps: '10-15',
    description: 'Classic bicep builder. Develops arm peak and overall bicep strength.',
    descriptionUrdu: 'بائی سیپس بنانے کا کلاسک طریقہ۔ بازو کی چوٹی اور طاقت بناتا ہے۔',
    instructions: [
      'Stand with dumbbells at sides, palms forward',
      'Curl weights up toward shoulders',
      'Squeeze bicep at top',
      'Lower slowly with control'
    ],
    calories: 80
  },
  {
    id: '7',
    name: 'Tricep Pushdown',
    nameUrdu: 'ٹرائی سیپ پش ڈاؤن',
    nameJapanese: 'トライセップスプッシュダウン',
    muscleGroup: 'Arms',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    bodyPart: 'Upper Body',
    youtubeId: 'vB5OHsJ3EME',
    thumbnail: 'https://img.youtube.com/vi/vB5OHsJ3EME/maxresdefault.jpg',
    duration: '25 min',
    sets: '3',
    reps: '12-15',
    description: 'Isolates triceps for maximum arm size. Essential for big arms.',
    descriptionUrdu: 'ٹرائی سیپس کو الگ کرتا ہے۔ بڑے بازوؤں کے لیے ضروری ہے۔',
    instructions: [
      'Stand at cable machine, bar at chest height',
      'Push bar down until arms are fully extended',
      'Squeeze triceps at bottom',
      'Return bar slowly to starting position'
    ],
    calories: 70
  },
  {
    id: '8',
    name: 'Leg Press',
    nameUrdu: 'لیگ پریس',
    nameJapanese: 'レッグプレス',
    muscleGroup: 'Legs',
    difficulty: 'Beginner',
    equipment: 'Machine',
    bodyPart: 'Lower Body',
    youtubeId: 'IZxyjW7MPJQ',
    thumbnail: 'https://img.youtube.com/vi/IZxyjW7MPJQ/maxresdefault.jpg',
    duration: '35 min',
    sets: '4',
    reps: '10-15',
    description: 'Machine-based quad developer. Great for beginners building leg strength.',
    descriptionUrdu: 'مشین پر مبنی کواڈ ورزش۔ ابتدائی طور پر ٹانگوں کی طاقت بنانے کے لیے بہترین۔',
    instructions: [
      'Sit in leg press machine, feet shoulder-width on platform',
      'Lower platform until knees are at 90 degrees',
      'Press through heels to extend legs',
      'Do not lock out knees at top'
    ],
    calories: 150
  },
  {
    id: '9',
    name: 'Cable Row',
    nameUrdu: 'کیبل رو',
    nameJapanese: 'ケーブルロウ',
    muscleGroup: 'Back',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    bodyPart: 'Upper Body',
    youtubeId: 'GZbfZ033f74',
    thumbnail: 'https://img.youtube.com/vi/GZbfZ033f74/maxresdefault.jpg',
    duration: '35 min',
    sets: '4',
    reps: '10-12',
    description: 'Builds back thickness and improves posture. Great for beginners.',
    descriptionUrdu: 'پشت کی موٹائی بناتا ہے اور کرنسی بہتر کرتا ہے۔ ابتدائی افراد کے لیے بہترین۔',
    instructions: [
      'Sit at cable row machine, feet on platform',
      'Pull handle to lower abdomen',
      'Squeeze shoulder blades together',
      'Return to start with straight back'
    ],
    calories: 110
  },
  {
    id: '10',
    name: 'Dumbbell Shoulder Press',
    nameUrdu: 'ڈمبل شولڈر پریس',
    nameJapanese: 'ダンベルショルダープレス',
    muscleGroup: 'Shoulders',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    bodyPart: 'Upper Body',
    youtubeId: 'qEwKCR5JCog',
    thumbnail: 'https://img.youtube.com/vi/qEwKCR5JCog/maxresdefault.jpg',
    duration: '30 min',
    sets: '3',
    reps: '10-12',
    description: 'Develops round, defined shoulders with independent arm training.',
    descriptionUrdu: 'گول، واضح کندھے بناتا ہے۔ آزاد بازو کی تربیت کے ساتھ۔',
    instructions: [
      'Sit or stand with dumbbells at shoulder height',
      'Press dumbbells overhead until arms extended',
      'Lower slowly back to shoulder height',
      'Keep core braced throughout'
    ],
    calories: 100
  },
  {
    id: '11',
    name: 'Romanian Deadlift',
    nameUrdu: 'رومانیائی ڈیڈلفٹ',
    nameJapanese: 'ルーマニアンデッドリフト',
    muscleGroup: 'Legs',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    bodyPart: 'Lower Body',
    youtubeId: 'JCXUYuzwNrM',
    thumbnail: 'https://img.youtube.com/vi/JCXUYuzwNrM/maxresdefault.jpg',
    duration: '40 min',
    sets: '4',
    reps: '8-12',
    description: 'Premier hamstring exercise. Develops posterior chain strength and flexibility.',
    descriptionUrdu: 'ہیمسٹرنگ کی بہترین ورزش۔ پوسٹیریئر چین کی طاقت اور لچک بناتا ہے۔',
    instructions: [
      'Stand holding barbell at hip height',
      'Hinge at hips, pushing them back',
      'Lower bar along legs, feeling hamstring stretch',
      'Drive hips forward to return to start'
    ],
    calories: 160
  },
  {
    id: '12',
    name: 'Plank',
    nameUrdu: 'پلانک',
    nameJapanese: 'プランク',
    muscleGroup: 'Core',
    difficulty: 'Beginner',
    equipment: 'None',
    bodyPart: 'Core',
    youtubeId: 'pSHjTRCQxIw',
    thumbnail: 'https://img.youtube.com/vi/pSHjTRCQxIw/maxresdefault.jpg',
    duration: '20 min',
    sets: '3',
    reps: '30-60 sec',
    description: 'Fundamental core stability exercise. Builds a strong foundation for all lifts.',
    descriptionUrdu: 'بنیادی کور استحکام ورزش۔ تمام لفٹس کے لیے مضبوط بنیاد بناتی ہے۔',
    instructions: [
      'Get in push-up position on forearms',
      'Keep body in straight line from head to heels',
      'Squeeze glutes and brace core',
      'Hold for prescribed time without sagging'
    ],
    calories: 50
  },
  {
    id: '13',
    name: 'Incline Dumbbell Press',
    nameUrdu: 'انکلائن ڈمبل پریس',
    nameJapanese: 'インクラインダンベルプレス',
    muscleGroup: 'Chest',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    bodyPart: 'Upper Body',
    youtubeId: '8iPEnn-ltC8',
    thumbnail: 'https://img.youtube.com/vi/8iPEnn-ltC8/maxresdefault.jpg',
    duration: '40 min',
    sets: '4',
    reps: '8-12',
    description: 'Targets upper chest for complete pec development and a full chest look.',
    descriptionUrdu: 'اوپری سینے کو نشانہ بناتا ہے مکمل پیک ڈیولپمنٹ کے لیے۔',
    instructions: [
      'Set bench to 30-45 degree incline',
      'Hold dumbbells above chest with arms extended',
      'Lower dumbbells to upper chest',
      'Press back to starting position'
    ],
    calories: 110
  },
  {
    id: '14',
    name: 'Lat Pulldown',
    nameUrdu: 'لیٹ پل ڈاؤن',
    nameJapanese: 'ラットプルダウン',
    muscleGroup: 'Back',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    bodyPart: 'Upper Body',
    youtubeId: 'CAwf7n6Luuc',
    thumbnail: 'https://img.youtube.com/vi/CAwf7n6Luuc/maxresdefault.jpg',
    duration: '35 min',
    sets: '4',
    reps: '10-12',
    description: 'Builds wide back and V-taper. Great pull-up alternative for beginners.',
    descriptionUrdu: 'چوڑی پشت اور V شکل بناتا ہے۔ ابتدائی افراد کے لیے پل اپ کا متبادل۔',
    instructions: [
      'Sit at lat pulldown machine, grip bar wide',
      'Pull bar down to upper chest',
      'Squeeze lats at bottom position',
      'Slowly return bar to top'
    ],
    calories: 90
  },
  {
    id: '15',
    name: 'Dips',
    nameUrdu: 'ڈپس',
    nameJapanese: 'ディップス',
    muscleGroup: 'Chest',
    difficulty: 'Intermediate',
    equipment: 'Dip Bar',
    bodyPart: 'Upper Body',
    youtubeId: 'yN6Q1UI_xkE',
    thumbnail: 'https://img.youtube.com/vi/yN6Q1UI_xkE/maxresdefault.jpg',
    duration: '30 min',
    sets: '4',
    reps: '8-15',
    description: 'Compound upper body movement targeting chest and triceps heavily.',
    descriptionUrdu: 'سینے اور ٹرائی سیپس کو بہت زیادہ نشانہ بناتا ہے۔',
    instructions: [
      'Grip parallel bars, arms fully extended',
      'Lower body by bending elbows, lean forward for chest',
      'Go until upper arms are parallel to floor',
      'Push back up to starting position'
    ],
    calories: 130
  },
  {
    id: '16',
    name: 'Calf Raises',
    nameUrdu: 'کاف ریزز',
    nameJapanese: 'カーフレイズ',
    muscleGroup: 'Legs',
    difficulty: 'Beginner',
    equipment: 'None',
    bodyPart: 'Lower Body',
    youtubeId: 'gwLzBJYoWlI',
    thumbnail: 'https://img.youtube.com/vi/gwLzBJYoWlI/maxresdefault.jpg',
    duration: '20 min',
    sets: '4',
    reps: '15-20',
    description: 'Develops lower leg muscles for complete leg development and athletic performance.',
    descriptionUrdu: 'نچلے ٹانگ کے پٹھوں کو بناتا ہے مکمل ٹانگ ڈیولپمنٹ کے لیے۔',
    instructions: [
      'Stand on edge of step or flat ground',
      'Rise up on toes as high as possible',
      'Squeeze calves at top',
      'Lower heels below step level for full stretch'
    ],
    calories: 60
  },
  {
    id: '17',
    name: 'Face Pulls',
    nameUrdu: 'فیس پلز',
    nameJapanese: 'フェイスプル',
    muscleGroup: 'Shoulders',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    bodyPart: 'Upper Body',
    youtubeId: 'rep-qVOkqgk',
    thumbnail: 'https://img.youtube.com/vi/rep-qVOkqgk/maxresdefault.jpg',
    duration: '25 min',
    sets: '3',
    reps: '15-20',
    description: 'Essential for shoulder health and rear delt development. Prevents injuries.',
    descriptionUrdu: 'کندھے کی صحت اور پچھلے ڈیلٹ ڈیولپمنٹ کے لیے ضروری۔ چوٹوں سے بچاتا ہے۔',
    instructions: [
      'Set cable at head height with rope attachment',
      'Pull rope toward face, elbows flared high',
      'Externally rotate at end position',
      'Return with control'
    ],
    calories: 70
  },
  {
    id: '18',
    name: 'Ab Crunch',
    nameUrdu: 'ایب کرنچ',
    nameJapanese: 'アブクランチ',
    muscleGroup: 'Core',
    difficulty: 'Beginner',
    equipment: 'None',
    bodyPart: 'Core',
    youtubeId: 'Xyd_fa5zoEU',
    thumbnail: 'https://img.youtube.com/vi/Xyd_fa5zoEU/maxresdefault.jpg',
    duration: '20 min',
    sets: '4',
    reps: '15-25',
    description: 'Classic abdominal exercise for building visible six-pack abs.',
    descriptionUrdu: 'سکس پیک ایبز کے لیے کلاسک پیٹ کی ورزش۔',
    instructions: [
      'Lie on back with knees bent, hands behind head',
      'Curl shoulders off floor, contracting abs',
      'Hold at top for 1 second',
      'Lower back down with control'
    ],
    calories: 55
  },
  {
    id: '19',
    name: 'Lunges',
    nameUrdu: 'لنجز',
    nameJapanese: 'ランジ',
    muscleGroup: 'Legs',
    difficulty: 'Beginner',
    equipment: 'None',
    bodyPart: 'Lower Body',
    youtubeId: 'QOVaHwm-Q6U',
    thumbnail: 'https://img.youtube.com/vi/QOVaHwm-Q6U/maxresdefault.jpg',
    duration: '30 min',
    sets: '3',
    reps: '12 each leg',
    description: 'Unilateral leg exercise for balanced development, stability and functional strength.',
    descriptionUrdu: 'متوازن ڈیولپمنٹ، استحکام اور فعال طاقت کے لیے یکطرفہ ٹانگ ورزش۔',
    instructions: [
      'Stand with feet together',
      'Step forward, lowering back knee toward floor',
      'Front thigh should be parallel to floor',
      'Push back to starting position'
    ],
    calories: 120
  },
  {
    id: '20',
    name: 'Push-Ups',
    nameUrdu: 'پش اپس',
    nameJapanese: 'プッシュアップ',
    muscleGroup: 'Chest',
    difficulty: 'Beginner',
    equipment: 'None',
    bodyPart: 'Upper Body',
    youtubeId: '_l3ySVKYVJ8',
    thumbnail: 'https://img.youtube.com/vi/_l3ySVKYVJ8/maxresdefault.jpg',
    duration: '20 min',
    sets: '4',
    reps: '15-20',
    description: 'The foundational upper body exercise. No equipment needed.',
    descriptionUrdu: 'بنیادی اوپری جسم کی ورزش۔ کوئی سامان درکار نہیں۔',
    instructions: [
      'Get in plank position with hands shoulder-width apart',
      'Lower chest to floor by bending elbows',
      'Keep body straight throughout movement',
      'Push back to starting position'
    ],
    calories: 80
  },
  {
    id: '21',
    name: 'Hammer Curls',
    nameUrdu: 'ہیمر کرلز',
    nameJapanese: 'ハンマーカール',
    muscleGroup: 'Arms',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    bodyPart: 'Upper Body',
    youtubeId: 'zC3nLlEvin4',
    thumbnail: 'https://img.youtube.com/vi/zC3nLlEvin4/maxresdefault.jpg',
    duration: '25 min',
    sets: '3',
    reps: '10-12',
    description: 'Builds brachialis and forearm thickness for bigger-looking arms overall.',
    descriptionUrdu: 'بریکیالیس اور بازو کی موٹائی بناتا ہے مجموعی طور پر بڑے نظر آنے والے بازوؤں کے لیے۔',
    instructions: [
      'Hold dumbbells with neutral grip (palms facing each other)',
      'Curl weights up keeping neutral grip',
      'Squeeze at top position',
      'Lower slowly'
    ],
    calories: 75
  },
  {
    id: '22',
    name: 'Bent Over Row',
    nameUrdu: 'بینٹ اوور رو',
    nameJapanese: 'ベントオーバーロウ',
    muscleGroup: 'Back',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    bodyPart: 'Upper Body',
    youtubeId: 'FWJR5Ve8bnQ',
    thumbnail: 'https://img.youtube.com/vi/FWJR5Ve8bnQ/maxresdefault.jpg',
    duration: '40 min',
    sets: '4',
    reps: '6-10',
    description: 'Builds back thickness and raw strength. One of the best compound back exercises.',
    descriptionUrdu: 'پشت کی موٹائی اور خام طاقت بناتا ہے۔ بہترین مرکب پشت ورزشوں میں سے ایک۔',
    instructions: [
      'Hinge at hips, holding barbell with overhand grip',
      'Pull bar to lower chest/upper abdomen',
      'Squeeze shoulder blades together at top',
      'Lower bar with control'
    ],
    calories: 160
  },
  {
    id: '23',
    name: 'Leg Extension',
    nameUrdu: 'لیگ ایکسٹینشن',
    nameJapanese: 'レッグエクステンション',
    muscleGroup: 'Legs',
    difficulty: 'Beginner',
    equipment: 'Machine',
    bodyPart: 'Lower Body',
    youtubeId: 'YyvSfVjQeL0',
    thumbnail: 'https://img.youtube.com/vi/YyvSfVjQeL0/maxresdefault.jpg',
    duration: '25 min',
    sets: '3',
    reps: '12-15',
    description: 'Isolates quadriceps for detailed quad development and knee strength.',
    descriptionUrdu: 'کواڈری سیپس کو الگ کرتا ہے تفصیلی کواڈ ڈیولپمنٹ کے لیے۔',
    instructions: [
      'Sit in leg extension machine, pad on front of ankles',
      'Extend legs until straight',
      'Hold briefly at top',
      'Lower with control'
    ],
    calories: 85
  },
  {
    id: '24',
    name: 'Cable Lateral Raise',
    nameUrdu: 'کیبل لیٹرل ریز',
    nameJapanese: 'ケーブルラテラルレイズ',
    muscleGroup: 'Shoulders',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    bodyPart: 'Upper Body',
    youtubeId: 'PPbMBhMKcgI',
    thumbnail: 'https://img.youtube.com/vi/PPbMBhMKcgI/maxresdefault.jpg',
    duration: '25 min',
    sets: '3',
    reps: '12-15',
    description: 'Best exercise for building wide, capped deltoids and shoulder width.',
    descriptionUrdu: 'چوڑے، گول ڈیلٹوئیڈز اور کندھے کی چوڑائی بنانے کی بہترین ورزش۔',
    instructions: [
      'Stand next to cable machine, grab low pulley',
      'Raise arm out to side until parallel to floor',
      'Pinky should be slightly higher than thumb',
      'Lower with control'
    ],
    calories: 65
  },
  {
    id: '25',
    name: 'Hanging Leg Raise',
    nameUrdu: 'ہینگنگ لیگ ریز',
    nameJapanese: 'ハンギングレッグレイズ',
    muscleGroup: 'Core',
    difficulty: 'Intermediate',
    equipment: 'Pull-up Bar',
    bodyPart: 'Core',
    youtubeId: 'hdng3Nm1x_E',
    thumbnail: 'https://img.youtube.com/vi/hdng3Nm1x_E/maxresdefault.jpg',
    duration: '25 min',
    sets: '4',
    reps: '10-15',
    description: 'Advanced core exercise developing lower abs and hip flexor strength.',
    descriptionUrdu: 'نچلے ایبز اور ہپ فلیکسر طاقت بناتا ہے۔ ترقی یافتہ کور ورزش۔',
    instructions: [
      'Hang from pull-up bar with arms extended',
      'Raise legs until parallel to floor or higher',
      'Control the movement, avoid swinging',
      'Lower legs slowly'
    ],
    calories: 95
  },
  {
    id: '26',
    name: 'Chest Fly',
    nameUrdu: 'چیسٹ فلائی',
    nameJapanese: 'チェストフライ',
    muscleGroup: 'Chest',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    bodyPart: 'Upper Body',
    youtubeId: 'eozdVDA78K0',
    thumbnail: 'https://img.youtube.com/vi/eozdVDA78K0/maxresdefault.jpg',
    duration: '30 min',
    sets: '3',
    reps: '12-15',
    description: 'Stretches and isolates the chest for maximum pec activation and growth.',
    descriptionUrdu: 'زیادہ سے زیادہ پیک ایکٹیویشن اور نشوونما کے لیے سینے کو کھینچتا اور الگ کرتا ہے۔',
    instructions: [
      'Lie on bench, dumbbells above chest with slight bend in elbows',
      'Open arms out wide in arc motion',
      'Feel stretch in chest at bottom',
      'Bring dumbbells back together'
    ],
    calories: 90
  },
  {
    id: '27',
    name: 'Skull Crushers',
    nameUrdu: 'اسکل کرشرز',
    nameJapanese: 'スカルクラッシャー',
    muscleGroup: 'Arms',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    bodyPart: 'Upper Body',
    youtubeId: 'NIyDA2fOOBM',
    thumbnail: 'https://img.youtube.com/vi/NIyDA2fOOBM/maxresdefault.jpg',
    duration: '30 min',
    sets: '4',
    reps: '10-12',
    description: 'Elite tricep mass builder. Develops the long head of the tricep for arm thickness.',
    descriptionUrdu: 'بہترین ٹرائی سیپس ماس بلڈر۔ بازو کی موٹائی کے لیے لمبے سر کو بناتا ہے۔',
    instructions: [
      'Lie on bench, hold barbell above chest with arms extended',
      'Lower bar toward forehead by bending elbows only',
      'Stop just above forehead',
      'Press back to starting position'
    ],
    calories: 100
  },
  {
    id: '28',
    name: 'Hip Thrust',
    nameUrdu: 'ہپ تھرسٹ',
    nameJapanese: 'ヒップスラスト',
    muscleGroup: 'Legs',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    bodyPart: 'Lower Body',
    youtubeId: 'xDmFkJxPzeM',
    thumbnail: 'https://img.youtube.com/vi/xDmFkJxPzeM/maxresdefault.jpg',
    duration: '35 min',
    sets: '4',
    reps: '10-15',
    description: 'Best glute builder available. Maximizes posterior chain development.',
    descriptionUrdu: 'بہترین گلوٹ بلڈر۔ پوسٹیریئر چین ڈیولپمنٹ کو زیادہ سے زیادہ کرتا ہے۔',
    instructions: [
      'Sit against bench, roll barbell over hips',
      'Plant feet flat, drive hips up explosively',
      'Squeeze glutes hard at top',
      'Lower hips back to floor'
    ],
    calories: 140
  },
  {
    id: '29',
    name: 'Arnold Press',
    nameUrdu: 'آرنلڈ پریس',
    nameJapanese: 'アーノルドプレス',
    muscleGroup: 'Shoulders',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    bodyPart: 'Upper Body',
    youtubeId: 'vJ2w851ZHRM',
    thumbnail: 'https://img.youtube.com/vi/vJ2w851ZHRM/maxresdefault.jpg',
    duration: '35 min',
    sets: '4',
    reps: '10-12',
    description: "Arnold Schwarzenegger's signature move. Hits all three deltoid heads.",
    descriptionUrdu: 'آرنلڈ شوارزنیگر کی خاص حرکت۔ تمام تین ڈیلٹوئیڈ سروں کو مارتی ہے۔',
    instructions: [
      'Hold dumbbells at shoulder height, palms facing you',
      'Press up while rotating palms outward',
      'At top, palms face forward',
      'Reverse rotation while lowering'
    ],
    calories: 115
  },
  {
    id: '30',
    name: 'Mountain Climbers',
    nameUrdu: 'ماؤنٹین کلائمبرز',
    nameJapanese: 'マウンテンクライマー',
    muscleGroup: 'Core',
    difficulty: 'Beginner',
    equipment: 'None',
    bodyPart: 'Full Body',
    youtubeId: 'nmwgirgXLYM',
    thumbnail: 'https://img.youtube.com/vi/nmwgirgXLYM/maxresdefault.jpg',
    duration: '20 min',
    sets: '4',
    reps: '30 sec',
    description: 'Full body cardio and core exercise. Burns fat while building abs.',
    descriptionUrdu: 'پورے جسم کی کارڈیو اور کور ورزش۔ چربی جلاتے ہوئے ایبز بناتا ہے۔',
    instructions: [
      'Get in high plank position',
      'Drive one knee toward chest',
      'Quickly switch legs in running motion',
      'Keep hips level throughout'
    ],
    calories: 150
  }
];

export const workoutPlans = [
  {
    id: 'plan1',
    name: 'Beginner Full Body',
    nameUrdu: 'ابتدائی پورے جسم کا پروگرام',
    nameJapanese: '初心者フルボディ',
    difficulty: 'Beginner',
    duration: '4 weeks',
    frequency: '3x per week',
    exercises: ['20', '6', '8', '18', '19', '12'],
    description: 'Perfect for gym newcomers. Build foundational strength with basic compound movements.',
    calories: 400,
    image: 'https://img.youtube.com/vi/_l3ySVKYVJ8/maxresdefault.jpg'
  },
  {
    id: 'plan2',
    name: 'Push Pull Legs',
    nameUrdu: 'پش پل ٹانگیں',
    nameJapanese: 'プッシュプルレッグス',
    difficulty: 'Intermediate',
    duration: '8 weeks',
    frequency: '6x per week',
    exercises: ['1', '5', '7', '2', '9', '3', '11'],
    description: 'The gold standard training split. Maximize muscle growth with this proven program.',
    calories: 600,
    image: 'https://img.youtube.com/vi/rT7DgCr-3pg/maxresdefault.jpg'
  },
  {
    id: 'plan3',
    name: 'Strength Power',
    nameUrdu: 'طاقت پاور',
    nameJapanese: 'ストレングスパワー',
    difficulty: 'Advanced',
    duration: '12 weeks',
    frequency: '5x per week',
    exercises: ['4', '3', '1', '5', '22'],
    description: 'Big 5 compound movements for raw strength. Based on powerlifting principles.',
    calories: 700,
    image: 'https://img.youtube.com/vi/op9kVnSso6Q/maxresdefault.jpg'
  },
  {
    id: 'plan4',
    name: 'Aesthetic Physique',
    nameUrdu: 'خوبصورت جسم',
    nameJapanese: 'アestheticフィジーク',
    difficulty: 'Intermediate',
    duration: '10 weeks',
    frequency: '5x per week',
    exercises: ['1', '13', '26', '2', '14', '3', '8', '5', '29'],
    description: 'Build a classic bodybuilding physique with balanced muscle development.',
    calories: 550,
    image: 'https://img.youtube.com/vi/8iPEnn-ltC8/maxresdefault.jpg'
  }
];
